---
exclude: '^(venv|\.vscode|neofetch)' # regex
repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: ["--wrap-summaries=125", "--wrap-descriptions=125"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: text-unicode-replacement-char
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        args: ["--print-width=135"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.254"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore, E501]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: ["--ignore-case", "--unique"]
        files: '^\.gitignore$'
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: ["-b", "master"]
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-tabs
        exclude_types: [makefile, binary]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: 65ea059268676338855129ec6c36b3e981d621da
    hooks:
      - id: CVE-2017-18342
      - id: remove-en-dashes
        exclude: do-updates-and-reboot.sh
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
      - id: remove-unicode-zero-width-space
