# https://github.com/psf/black#configuration-format
[tool.black]
exclude = '(venv|.vscode)'
include = '\.pyi?$'
line-length = 132
#skip-string-normalization = true
target-version = ['py38']

[tool.ruff]
fixable = ["ALL"]
select = ["E", "F", "Q", "S"]
ignore = ["E501", "S311", "S603", "S608"]

[tool.ruff.per-file-ignores]
"**/__init__.py" = ["F401"]
